### ISSUE TITLE
Missing chunk should error out

### ISSUE THREAD

**Issue by OverkillGuy** [OverkillGuy/qrxfil#14]
With current naive implementation, the list of chunks given will be iterated on for decoding, but we won't notice if a chunk was missing.

Add chunks checking logic so that before restoring, we error out gracefully when chunks are missing.

Note this does not include managing out-of-order scanning, which is #13.

**Comment by danieleades** [comment]
`BTreeMap` is probably also your friend here (as well as #13)

**Comment by OverkillGuy** [comment]
Ongoing work in branch [missing-chunk#14](https://github.com/OverkillGuy/qrxfil/tree/missing-chunk%2314) using `HashSet` and its `.difference()` function, actually.

**Comment by danieleades** [comment]
> Ongoing work in branch [missing-chunk#14](https://github.com/OverkillGuy/qrxfil/tree/missing-chunk%2314) using `HashSet` and its `.difference()` function, actually.

ah ok. Very similiar functionality in that they support almost exactly the same interface, including set operations. One key difference- A `BTreeMap` or `BTreeSet` will give you ordering. This is useful if you want to

- read the entries in order
- check which entries are missing
- find the 'last' or 'first' entry

`HashSet` is of course unordered, which makes it slightly more efficient for entry and lookups by value, but much slower for any searches or operations for which ordering is important (since you'll have to sort yourself every time)

You would use `BtreeMap` (key-value store) to store the entries by some integer (which you would presumably parse from the header), or `BTreeSet` to store the bare  values, provided you can calculate the ordering between any two entries (by implementing the `Ord` trait for your entries).

**Comment by OverkillGuy** [comment]
So, while I know exactly what I want to do, Rust isn't playing nice:

```rust
fn check_chunk_range(chunks: &Vec<EncodedChunk>, total: u16) -> Result<(), RestoreError> {
    let mut actual_chunk_ids = HashSet::<u16>::with_capacity(total as usize);
    for chunk in chunks {
        actual_chunk_ids.insert(chunk.id);
    }
    let expected_chunk_ids: HashSet<u16> = (1..total).collect();
    if actual_chunk_ids == expected_chunk_ids {
        return Ok(());
    }
    if actual_chunk_ids.is_subset(&expected_chunk_ids) {
        // FIXME: HashSet.difference() gives Vec<&u16>, no conversion to missing_chunk: Vec<u16>
        let missing_ids = expected_chunk_ids
            .difference(&actual_chunk_ids)
            .collect::<Vec<&u16>>();
        return Err(RestoreError::MissingChunk {
            expected_total: total,
            missing_chunk_ids: missing_ids,
        });
    }

    Ok(())
}
```
So, the `difference()` operation gives a `Vec<&u16>` but I can't find good ways to convert it back. Any ideas?

**Comment by OverkillGuy** [comment]
... just found it via `cloned().collect`:

```rust
fn check_chunk_range(chunks: &Vec<EncodedChunk>, total: u16) -> Result<(), RestoreError> {
    let mut actual_chunk_ids = HashSet::<u16>::with_capacity(total as usize);
    for chunk in chunks {
        actual_chunk_ids.insert(chunk.id);
    }
    let expected_chunk_ids: HashSet<u16> = (1..total).collect();
    if actual_chunk_ids == expected_chunk_ids {
        return Ok(());
    }
    if actual_chunk_ids.is_subset(&expected_chunk_ids) {
        let missing_ids = expected_chunk_ids
            .difference(&actual_chunk_ids)
            .cloned()
            .collect::<Vec<u16>>();
        return Err(RestoreError::MissingChunk {
            expected_total: total,
            missing_chunk_ids: missing_ids,
        });
    }

    Ok(())
}
```

**Comment by danieleades** [comment]
since `u16` implements the `Copy` trait, you can used `copied()` instead of `cloned()`

**Comment by OverkillGuy** [comment]
> since `u16` implements the `Copy` trait, you can used `copied()` instead of `cloned()`

Yeah I need to understand what's the difference, they seem functionally equivalent from afar. I expect that `copy` is related to the "Copiable" (primitives not object) trait, so that passing an integer by value does a copy, whereas clone is like python's `from copy import deepcopy`?

**Comment by danieleades** [comment]
> > since `u16` implements the `Copy` trait, you can used `copied()` instead of `cloned()`
> 
> Yeah I need to understand what's the difference, they seem functionally equivalent from afar. I expect that `copy` is related to the "Copiable" (primitives not object) trait, so that passing an integer by value does a copy, whereas clone is like python's `from copy import deepcopy`?

both 'copy' and 'clone' are 'deep' in that sense. the difference is that 'copy' is cheap. So cheap, in fact, that 'copy' types will copy *implicitly* in certain situations.

for example

```rust
def boolean_function(&self) -> &bool {
    &self.boolean
}
```

can be changed to 

```rust
def boolean_function(&self) -> bool {
    self.boolean
}
```

instead of complaining that you've moving an item out of a reference, it'll just implicitly 'copy' the bool since copying bools is cheap (cheaper in fact than passing a reference!)

**Comment by OverkillGuy** [comment]
Whoops, this commit was meant to address #4 not 14
